version: '3.3'
services:
  fe:
    build: .
    container_name: fe
    volumes:
      - ./build:/app:rw
      - ./.env:/app/.env:rw
    ports:
      - 9999:80
    environment:
      - INSTAGRAM_API_CLIENT_ID
      - BASE_URL